### PR TITLE
Display all local and remote video

### PR DESCRIPTION
**Pull request by ZZYSonny**
Reason for PR: When I am testing c2c with my laptop and my phone, both my Phone and my PC show a pixelated face from me. And the face takes up the whole screen. However, in PiP mode (all video displayed and original aspect ratio), the video isn't too bad.
(btw I am also working on a PR on codec and bitrate to improve video quality)

In this PR:
The wrapper of myLocalVideo will automatically fit the aspect ratio of local video.
RemoteVideo will fit the screen in the original aspect ratio. (grey background will be shown if they don't match perfectly.)
"my-video-wrap-width" and "my-video-wrap-height" are tested on my laptop and phone. These two numbers seems to work good enough for me. But I am open to any changes.

### CODE REVIEW

**Comment by miroslavpejic85** [comment]
Hey @ZZYSonny!

I want to express my gratitude for your pull request (PR). It's greatly appreciated!

You've brought up an excellent point regarding the aspect ratio feature, which is present in other MiroTalk versions but seems to be missing here. What about to make it optional ([commit](https://github.com/miroslavpejic85/mirotalkc2c/pull/8/commits/a9eaf67210e01ad0ac45a0bc2044a854a4d5e9ef)). This way, users can choose whether they want to activate this feature or not, which adds a nice touch of customization to our product.

Thank you once again for your contribution, and I look forward to seeing this enhancement in action. Keep up the great work! 😊🚀

c2c-aspect-ratio

**Comment by ZZYSonny** [comment]
Hi @miroslavpejic85 
Thank you for making this PR even better. Allowing users to toggle aspect ratio is great.

I notice you are explicitly setting the width and height on a mobile device. And if aspect ratio is toggled on, grey background will appear in that banner. What about removing line 660-663 and also making the local video banner fit to the aspect ratio of local video (just like on pc)?

Before: 

After:

**Comment by miroslavpejic85** [comment]
Maybe you are testing it on an Android mobile, but on an iOS mobile, I need to keep it to make it work properly.
Try with last commit if show correctly? Thank you!

**Comment by ZZYSonny** [comment]
With the latest commit, the local banner is showing correctly. 
Thanks for fixing!

**Pull request merged**
